services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]